"""Change image_url to image_data and add image_filename

Revision ID: 2d2ae57bad50
Revises: 1323e067202f
Create Date: 2025-12-06 18:47:01.013620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d2ae57bad50'
down_revision: Union[str, Sequence[str], None] = '1323e067202f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image_data', sa.LargeBinary(), nullable=True))
    op.add_column('posts', sa.Column('image_filename', sa.String(), nullable=True))
    op.drop_column('posts', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('posts', 'image_filename')
    op.drop_column('posts', 'image_data')
    # ### end Alembic commands ###
